version: '3.5'
services:

  # #PHP Service
  app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html

  # node:
  #   image: node:latest
  #   working_dir: /build
  #   volumes:
  #     - ./:/build

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/

  adminer:
    container_name: adminer
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080

#Volumes
volumes:
  dbdata:
